In [114]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm

In [115]:
df = pd.read_csv('/home/suman/Desktop/data/german-credit.txt', sep = " ")
df.columns = ["Status_of_existing_checking_account","Duration_in_month", "Credit_history", "Purpose", "Credit_amount",
             "Savings_account", "Present_employment_since", "Installment_rate_in_percentage_of_disposable_income", "Personal_status_and_sex",
             "Other_debtors_or_guarantors", "Present_residence_since", "Property", "Age_in_years","Other_installment_plans",
              "Housing", "Number_of_existing_credits_at_this_bank", "Job", "Number_of_people_being_liable_to_provide_maintenance_for", 
             "Telephone", "foreign_worker", "status"]

In [116]:
df.head()

Status_of_existing_checking_account  Duration_in_month Credit_history  \
0                                 A12                 48            A32   
1                                 A14                 12            A34   
2                                 A11                 42            A32   
3                                 A11                 24            A33   
4                                 A14                 36            A32   

  Purpose  Credit_amount Savings_account Present_employment_since  \
0     A43           5951             A61                      A73   
1     A46           2096             A61                      A74   
2     A42           7882             A61                      A74   
3     A40           4870             A61                      A73   
4     A46           9055             A65                      A73   

   Installment_rate_in_percentage_of_disposable_income  \
0                                                  2     
1                                                  2     
2                                                  2     
3                                                  3     
4                                                  2     

  Personal_status_and_sex Other_debtors_or_guarantors  ...    Property  \
0                     A92                        A101  ...        A121   
1                     A93                        A101  ...        A121   
2                     A93                        A103  ...        A122   
3                     A93                        A101  ...        A124   
4                     A93                        A101  ...        A124   

  Age_in_years  Other_installment_plans Housing  \
0           22                     A143    A152   
1           49                     A143    A152   
2           45                     A143    A153   
3           53                     A143    A153   
4           35                     A143    A153   

  Number_of_existing_credits_at_this_bank   Job  \
0                                       1  A173   
1                                       1  A172   
2                                       1  A173   
3                                       2  A173   
4                                       1  A172   

  Number_of_people_being_liable_to_provide_maintenance_for  Telephone  \
0                                                  1             A191   
1                                                  2             A191   
2                                                  2             A191   
3                                                  2             A191   
4                                                  2             A192   

  foreign_worker status  
0           A201      2  
1           A201      1  
2           A201      1  
3           A201      2  
4           A201      1  

[5 rows x 21 columns]

In [117]:
cat_columns = df.select_dtypes(['object']).columns

In [118]:
for col_names  in cat_columns:
    if(df[col_names].dtype == 'object'):
        df[col_names] = df[col_names].astype('category')
        df[col_names] = df[col_names].cat.codes

In [119]:
df.head()

Status_of_existing_checking_account  Duration_in_month  Credit_history  \
0                                    1                 48               2   
1                                    3                 12               4   
2                                    0                 42               2   
3                                    0                 24               3   
4                                    3                 36               2   

   Purpose  Credit_amount  Savings_account  Present_employment_since  \
0        4           5951                0                         2   
1        7           2096                0                         3   
2        3           7882                0                         3   
3        0           4870                0                         2   
4        7           9055                4                         2   

   Installment_rate_in_percentage_of_disposable_income  \
0                                                  2     
1                                                  2     
2                                                  2     
3                                                  3     
4                                                  2     

   Personal_status_and_sex  Other_debtors_or_guarantors   ...    Property  \
0                        1                            0   ...           0   
1                        2                            0   ...           0   
2                        2                            2   ...           1   
3                        2                            0   ...           3   
4                        2                            0   ...           3   

   Age_in_years  Other_installment_plans  Housing  \
0            22                        2        1   
1            49                        2        1   
2            45                        2        2   
3            53                        2        2   
4            35                        2        2   

   Number_of_existing_credits_at_this_bank  Job  \
0                                        1    2   
1                                        1    1   
2                                        1    2   
3                                        2    2   
4                                        1    1   

   Number_of_people_being_liable_to_provide_maintenance_for  Telephone  \
0                                                  1                 0   
1                                                  2                 0   
2                                                  2                 0   
3                                                  2                 0   
4                                                  2                 1   

   foreign_worker  status  
0               0       2  
1               0       1  
2               0       1  
3               0       2  
4               0       1  

[5 rows x 21 columns]

In [120]:
X = np.array(df.drop(['status'], axis = 1))
y = np.array(df['status'])

In [121]:
scalar = StandardScaler()
scaled_X = scalar.fit_transform(X)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [122]:
X

array([[ 1, 48,  2, ...,  1,  0,  0],
       [ 3, 12,  4, ...,  2,  0,  0],
       [ 0, 42,  2, ...,  2,  0,  0],
       ...,
       [ 3, 12,  2, ...,  1,  0,  0],
       [ 0, 45,  2, ...,  1,  1,  0],
       [ 1, 45,  4, ...,  1,  0,  0]])

In [131]:
X = scaled_X
X

array([[-0.4604147 ,  2.24755338, -0.50228581, ..., -0.42854322,
        -0.8222983 , -0.19611614],
       [ 1.13112262, -0.74010176,  1.34590397, ...,  2.33348694,
        -0.8222983 , -0.19611614],
       [-1.25618336,  1.74961086, -0.50228581, ...,  2.33348694,
        -0.8222983 , -0.19611614],
       ...,
       [ 1.13112262, -0.74010176, -0.50228581, ..., -0.42854322,
        -0.8222983 , -0.19611614],
       [-1.25618336,  1.99858212, -0.50228581, ..., -0.42854322,
         1.21610369, -0.19611614],
       [-0.4604147 ,  1.99858212,  1.34590397, ..., -0.42854322,
        -0.8222983 , -0.19611614]])

In [124]:
# scaled_X.mean(axis = 0)
# scaled_X.std(axis = 0)


In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, shuffle=False)

In [126]:
clf = svm.SVC()

In [127]:
clf.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [128]:
clf.predict(X_test)

array([1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1,
       2, 2])

In [129]:
clf.score(X_test,y_test)

0.765

In [134]:
clf.predict([[6,1,48,2,4,595100,0,2,2,1,0,0,22,2,1,1,2,1,0,0]])

array([1])